[pytest]
addopts =
    --junitxml=reports/junit/pytest-results.xml
    --cov=appname
    --cov-report=term-missing
    --cov-report=xml:reports/coverage/coverage.xml
    --cov-report=html:reports/coverage/html
testpaths = tests
